-- 000004_baseline_lotto_n3_schema.up.sql
--
-- BASELINE MIGRATION (idempotent). The Lotto N3 game domain tables were originally
-- created outside any migration framework (GORM auto-migrate / manual DDL) and were
-- therefore "orphans": not tracked by the backend golang-migrate set nor by the
-- reward_batch Liquibase changelog.
--
-- This migration adopts them into the backend migration history WITHOUT altering any
-- existing data. Every statement uses IF NOT EXISTS so that:
--   * on an existing database (staging) it is a safe no-op (tables already present),
--   * on a fresh database it recreates the schema faithfully.
--
-- Table DDL below reflects the live schema on lotto_stg as of migration 000003.
-- FK dependency order: lotto_n3_game -> lotto_n3_period -> n3_orders
--                      -> n3_order_items -> n3_order_items_bet.
--
-- Note: `icon` is text here (already converted from bytea in 000003). On a fresh DB
-- this baseline creates it as text directly, so 000003's guard becomes a no-op.

-- 1) lotto_n3_game --------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.lotto_n3_game (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type       character varying,
    name       character varying NOT NULL,
    icon       text,
    max_bet    integer,
    min_bet    integer,
    earn_rate  json NOT NULL,
    status     character varying,
    created_at timestamp without time zone,
    updated_at timestamp without time zone
);
CREATE INDEX IF NOT EXISTS lotto_n3_game_name_idx ON public.lotto_n3_game (name);

-- 2) lotto_n3_period ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.lotto_n3_period (
    id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id            bigint NOT NULL,
    open_at            timestamp without time zone NOT NULL,
    close_at           timestamp without time zone NOT NULL,
    override_earn_rate json,
    created_at         timestamp without time zone NOT NULL,
    updated_at         timestamp without time zone,
    CONSTRAINT lotto_n3_period_lotto_n3_game_fk
        FOREIGN KEY (game_id) REFERENCES public.lotto_n3_game (id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

-- 3) n3_orders ------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.n3_orders (
    id          uuid PRIMARY KEY,
    type        character varying,
    state       character varying,
    created_at  timestamp without time zone,
    updated_at  timestamp without time zone,
    description character varying,
    user_id     bigint,
    expired_at  timestamp without time zone,
    game_id     bigint NOT NULL,
    period_id   bigint NOT NULL,
    total_amt   real,
    CONSTRAINT n3_orders_lotto_n3_game_fk
        FOREIGN KEY (game_id) REFERENCES public.lotto_n3_game (id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT n3_orders_lotto_n3_period_fk
        FOREIGN KEY (period_id) REFERENCES public.lotto_n3_period (id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT n3_orders_users_fk
        FOREIGN KEY (user_id) REFERENCES public.users (id)
        ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS n3_orders_game_id_idx   ON public.n3_orders (game_id);
CREATE INDEX IF NOT EXISTS n3_orders_period_id_idx ON public.n3_orders (period_id);
CREATE INDEX IF NOT EXISTS n3_orders_user_id_idx   ON public.n3_orders (user_id);

-- 4) n3_order_items -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.n3_order_items (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    n3_orders_id uuid NOT NULL,
    type         character varying NOT NULL,
    earn_rate    real NOT NULL,
    is_paid      boolean,
    created_at   timestamp without time zone,
    updated_at   timestamp without time zone,
    amount       real,
    CONSTRAINT n3_order_items_n3_orders_fk
        FOREIGN KEY (n3_orders_id) REFERENCES public.n3_orders (id)
        ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS n3_order_items_n3_orders_id_idx ON public.n3_order_items (n3_orders_id);

-- 5) n3_order_items_bet ---------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.n3_order_items_bet (
    id      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id bigint NOT NULL,
    number  character varying(4),
    amount  real,
    CONSTRAINT n3_order_items_bet_n3_order_items_fk
        FOREIGN KEY (item_id) REFERENCES public.n3_order_items (id)
        ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS n3_order_items_bet_item_id_idx ON public.n3_order_items_bet (item_id);
CREATE INDEX IF NOT EXISTS n3_order_items_bet_number_idx  ON public.n3_order_items_bet (number, item_id);
