-- 000005_reward_baseline.up.sql
--
-- BASELINE MIGRATION (idempotent) for the REWARD domain tables.
--
-- These tables were originally owned by reward_batch's Liquibase changelog
-- (changesets 0001–0013). As part of consolidating all schema into this single
-- golang-migrate source of truth, they are adopted here WITHOUT altering data.
--
-- Every statement uses IF NOT EXISTS so that:
--   * on an existing database (staging, data-bearing) it is a safe no-op,
--   * on a fresh database it recreates the reward schema faithfully.
--
-- DDL below reflects the LIVE schema on lotto_stg (Liquibase at 0013) captured
-- 2026-09-30 — see docs/stg-snapshot/reward-ddl-raw.txt.
--
-- FK dependency order (must run AFTER 000004 which creates n3_orders):
--   lotto_draw_result
--     -> lotto_draw_prize_result        (FK n3_orders, draw_result)
--        -> lotto_draw_prize_result_item
--           -> lotto_draw_prize_result_item_bet
--   lotto_batch_run (independent)

-- 1) lotto_draw_result ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.lotto_draw_result (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title               character varying(255) NOT NULL,
    six_digit           character varying(6),
    four_digit          character varying(64),
    suffix_three_digit  character varying(255),
    suffix_two_digit    character varying(255),
    two_digit           character varying(255),
    animal              character varying(128),
    draw_type           character varying(32) NOT NULL,
    draw_date           date NOT NULL,
    draw_id             bigint,
    scraped_at_utc      timestamp without time zone,
    created_at          timestamp without time zone NOT NULL,
    status              character varying(32) NOT NULL DEFAULT 'IMPORTED',
    source_ref          character varying(255),
    publication_version integer NOT NULL DEFAULT 1,
    published_at        timestamp without time zone,
    updated_at          timestamp without time zone
);
CREATE INDEX        IF NOT EXISTS idx_lotto_draw_result_published_at ON public.lotto_draw_result (published_at);
CREATE UNIQUE INDEX IF NOT EXISTS uk_lotto_draw_result_draw_date_type ON public.lotto_draw_result (draw_date, draw_type);

-- 2) lotto_draw_prize_result ----------------------------------------------------
CREATE TABLE IF NOT EXISTS public.lotto_draw_prize_result (
    id                       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id                  bigint NOT NULL,
    period_id                bigint NOT NULL,
    n3_orders_id             uuid NOT NULL,
    matched_count            integer,
    processed                boolean DEFAULT false,
    batch_run_id             uuid,
    draw_result_id           bigint,
    evaluation_status        character varying(32),
    settlement_status        character varying(32),
    idempotency_key          character varying(128),
    result_version           integer NOT NULL DEFAULT 1,
    evaluated_at             timestamp without time zone,
    settlement_ready_at      timestamp without time zone,
    last_error               text,
    created_at               timestamp without time zone,
    updated_at               timestamp without time zone,
    processed_bet_count      integer NOT NULL DEFAULT 0,
    winning_bet_count        integer NOT NULL DEFAULT 0,
    total_prize_amount       numeric NOT NULL DEFAULT 0,
    is_prize                 boolean NOT NULL DEFAULT false,
    wallet_settlement_id     character varying(128),
    settlement_attempts      integer NOT NULL DEFAULT 0,
    settled_at               timestamp without time zone,
    settlement_attempted_at  timestamp without time zone,
    CONSTRAINT fk_lotto_draw_prize_result_n3_orders
        FOREIGN KEY (n3_orders_id) REFERENCES public.n3_orders (id)
        ON UPDATE RESTRICT ON DELETE CASCADE,
    CONSTRAINT fk_lotto_draw_prize_result_draw_result
        FOREIGN KEY (draw_result_id) REFERENCES public.lotto_draw_result (id)
        ON UPDATE RESTRICT ON DELETE RESTRICT
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_lotto_draw_prize_result_order_draw_version
    ON public.lotto_draw_prize_result (n3_orders_id, draw_result_id, result_version);
CREATE UNIQUE INDEX IF NOT EXISTS uk_lotto_draw_prize_result_idempotency_key
    ON public.lotto_draw_prize_result (idempotency_key);
CREATE INDEX        IF NOT EXISTS idx_lotto_draw_prize_result_batch_run_id
    ON public.lotto_draw_prize_result (batch_run_id);
CREATE INDEX        IF NOT EXISTS idx_lotto_draw_prize_result_is_prize
    ON public.lotto_draw_prize_result (is_prize);
-- partial unique index: HARD GUARANTEE against double-payment (Card 8 / changelog 0011)
CREATE UNIQUE INDEX IF NOT EXISTS uk_lotto_draw_prize_result_wallet_settlement_id
    ON public.lotto_draw_prize_result (wallet_settlement_id) WHERE (wallet_settlement_id IS NOT NULL);
CREATE INDEX        IF NOT EXISTS idx_lotto_draw_prize_result_settlement_attempted_at
    ON public.lotto_draw_prize_result (settlement_attempted_at);
CREATE INDEX        IF NOT EXISTS idx_lotto_draw_prize_result_game_period_eval_status
    ON public.lotto_draw_prize_result (game_id, period_id, evaluation_status);
CREATE INDEX        IF NOT EXISTS idx_lotto_draw_prize_result_game_period_settle_status
    ON public.lotto_draw_prize_result (game_id, period_id, settlement_status);

-- 3) lotto_draw_prize_result_item -----------------------------------------------
CREATE TABLE IF NOT EXISTS public.lotto_draw_prize_result_item (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lotto_draw_prize_result bigint NOT NULL,
    won_prize_amount        numeric NOT NULL,
    processed_at            timestamp without time zone NOT NULL,
    is_prize                boolean,
    item_id                 bigint,
    evaluation_status       character varying(32),
    matched_rule_code       character varying(64),
    result_version          integer NOT NULL DEFAULT 1,
    created_at              timestamp without time zone,
    updated_at             timestamp without time zone,
    CONSTRAINT fk_lotto_draw_prize_result_item_prize_result
        FOREIGN KEY (lotto_draw_prize_result) REFERENCES public.lotto_draw_prize_result (id)
        ON UPDATE RESTRICT ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_lotto_draw_prize_result_item_item_id
    ON public.lotto_draw_prize_result_item (item_id);
CREATE INDEX IF NOT EXISTS idx_lotto_draw_prize_result_item_eval_status
    ON public.lotto_draw_prize_result_item (evaluation_status);

-- 4) lotto_draw_prize_result_item_bet -------------------------------------------
CREATE TABLE IF NOT EXISTS public.lotto_draw_prize_result_item_bet (
    id                              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lotto_draw_prize_result_item_id bigint NOT NULL,
    bet_id                          bigint NOT NULL,
    amount                          numeric NOT NULL,
    prize_rate                      numeric NOT NULL,
    total_prize_amount              numeric NOT NULL,
    processed_at                    timestamp without time zone NOT NULL,
    bet_number                      character varying(16),
    bet_type                        character varying(32),
    evaluation_status               character varying(32),
    matched_rule_code               character varying(64),
    result_version                  integer NOT NULL DEFAULT 1,
    created_at                      timestamp without time zone,
    updated_at                      timestamp without time zone,
    CONSTRAINT fk_lotto_draw_prize_result_item_bet_result_item
        FOREIGN KEY (lotto_draw_prize_result_item_id) REFERENCES public.lotto_draw_prize_result_item (id)
        ON UPDATE RESTRICT ON DELETE CASCADE
);
CREATE INDEX        IF NOT EXISTS idx_lotto_draw_prize_result_item_bet_eval_status
    ON public.lotto_draw_prize_result_item_bet (evaluation_status);
CREATE UNIQUE INDEX IF NOT EXISTS uk_lotto_draw_prize_result_item_bet_result_bet_version
    ON public.lotto_draw_prize_result_item_bet (lotto_draw_prize_result_item_id, bet_id, result_version);
CREATE INDEX        IF NOT EXISTS idx_lotto_draw_prize_result_item_bet_bet_id
    ON public.lotto_draw_prize_result_item_bet (bet_id);

-- 5) lotto_batch_run ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.lotto_batch_run (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_execution_id bigint,
    status           character varying(32) NOT NULL DEFAULT 'PENDING',
    draw_date        date,
    draw_type        character varying(32),
    draw_result_id   bigint,
    created_at       timestamp without time zone NOT NULL DEFAULT now(),
    updated_at       timestamp without time zone,
    failure_reason   text
);
CREATE INDEX IF NOT EXISTS idx_lotto_batch_run_status           ON public.lotto_batch_run (status);
CREATE INDEX IF NOT EXISTS idx_lotto_batch_run_job_execution_id ON public.lotto_batch_run (job_execution_id);
